In [2]:
# Pandas

In [3]:
%pip install pandas

Requirement already satisfied: pandas in ./programming/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in ./programming/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./programming/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./programming/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [60]:
# 1D data structures in Pandas

In [4]:
# Pandas Series

In [ ]:
# A Pandas Series is a one-dimensional labeled array capable of holding 
# any data type (integers, strings, floats, Python objects, etc.).

# Each element has:
# Data (values)
# Label (index)

In [49]:
# Creating a Pandas Series

In [50]:
# 1. From a List

In [5]:
import pandas as pd

In [6]:
s = pd.Series([10, 20, 30])

In [7]:
s

0    10
1    20
2    30
dtype: int64

In [51]:
# 2. With Custom Index

In [52]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [53]:
s

a    10
b    20
c    30
dtype: int64

In [54]:
# 3. From a Dictionary

In [55]:
data = {'a': 10, 'b': 20, 'c': 30}
s = pd.Series(data)

In [56]:
s

a    10
b    20
c    30
dtype: int64

In [57]:
# 4. From a Single Value

In [58]:
s = pd.Series(5, index=[0,1,2,3])

In [59]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [61]:
# Important Attributes

In [62]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [63]:
s

a    10
b    20
c    30
dtype: int64

In [64]:
s.values   # returns data

array([10, 20, 30])

In [65]:
s.index    # returns index labels

Index(['a', 'b', 'c'], dtype='str')

In [66]:
s.dtype    # data type

dtype('int64')

In [67]:
s.shape    # size (1D)

(3,)

In [68]:
# Basic Data Manipulation

In [69]:
# 1. Arithmetic Operations

In [70]:
s = pd.Series([1,2,3])
print(s * 2)

0    2
1    4
2    6
dtype: int64

In [71]:
# 2. Handling Missing Values

In [72]:
s = pd.Series([1, None, 3])

In [73]:
s.isnull()     # detect missing

0    False
1     True
2    False
dtype: bool

In [74]:
s.dropna()     # remove missing

0    1.0
2    3.0
dtype: float64

In [75]:
s.fillna(0)    # replace missing

0    1.0
1    0.0
2    3.0
dtype: float64

In [76]:
# Value Counts

In [77]:
s = pd.Series([1,2,2,3,3,3])
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [78]:
# Indexing

In [84]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [85]:
# Indexing by Label

In [86]:
s['a']

np.int64(10)

In [89]:
# 2D data structures in Pandas

In [8]:
data = {
    "Customer_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Amit", "Sneha", "Priya", "Kiran"],
    "Age": [25, 30, None, 28, 40],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai"],
    "Salary": [50000, 60000, 55000, None, 65000]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
print(df)

   Customer_ID   Name   Age    City   Salary
0          101  Rahul  25.0    Pune  50000.0
1          102   Amit  30.0  Mumbai  60000.0
2          103  Sneha   NaN    Pune  55000.0
3          104  Priya  28.0   Delhi      NaN
4          105  Kiran  40.0  Mumbai  65000.0

In [11]:
# Convert DataFrame to CSV

In [12]:
df.to_csv("customer_data.csv", index=False)

In [13]:
# Load Dataset from CSV

In [14]:
df = pd.read_csv("customer_data.csv")
print(df)

   Customer_ID   Name   Age    City   Salary
0          101  Rahul  25.0    Pune  50000.0
1          102   Amit  30.0  Mumbai  60000.0
2          103  Sneha   NaN    Pune  55000.0
3          104  Priya  28.0   Delhi      NaN
4          105  Kiran  40.0  Mumbai  65000.0

In [15]:
# Data Understanding (EDA)

In [16]:
print(df.head())

   Customer_ID   Name   Age    City   Salary
0          101  Rahul  25.0    Pune  50000.0
1          102   Amit  30.0  Mumbai  60000.0
2          103  Sneha   NaN    Pune  55000.0
3          104  Priya  28.0   Delhi      NaN
4          105  Kiran  40.0  Mumbai  65000.0

In [17]:
print(df.tail())

   Customer_ID   Name   Age    City   Salary
0          101  Rahul  25.0    Pune  50000.0
1          102   Amit  30.0  Mumbai  60000.0
2          103  Sneha   NaN    Pune  55000.0
3          104  Priya  28.0   Delhi      NaN
4          105  Kiran  40.0  Mumbai  65000.0

In [18]:
print(df.shape)

(5, 5)

In [19]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'City', 'Salary'], dtype='str')

In [20]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5 non-null      int64
 1   Name         5 non-null      str
 2   Age          4 non-null      float64
 3   City         5 non-null      str
 4   Salary       4 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 328.0 bytes
None

In [21]:
print(df.describe())

       Customer_ID    Age        Salary
count     5.000000   4.00      4.000000
mean    103.000000  30.75  57500.000000
std       1.581139   6.50   6454.972244
min     101.000000  25.00  50000.000000
25%     102.000000  27.25  53750.000000
50%     103.000000  29.00  57500.000000
75%     104.000000  32.50  61250.000000
max     105.000000  40.00  65000.000000

In [22]:
# Handling Missing Values

In [23]:
print(df.isnull().sum())

Customer_ID    0
Name           0
Age            1
City           0
Salary         1
dtype: int64

In [24]:
# Fill missing values

In [25]:
# Fill Age with mean
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [26]:
df

   Customer_ID   Name    Age    City   Salary
0          101  Rahul  25.00    Pune  50000.0
1          102   Amit  30.00  Mumbai  60000.0
2          103  Sneha  30.75    Pune  55000.0
3          104  Priya  28.00   Delhi      NaN
4          105  Kiran  40.00  Mumbai  65000.0

In [27]:
# Fill Salary with median
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [28]:
# Data Cleaning

In [29]:
df = df.drop_duplicates()

In [30]:
df.rename(columns={"Name": "Customer_Name"}, inplace=True)

In [31]:
df

   Customer_ID Customer_Name    Age    City   Salary
0          101         Rahul  25.00    Pune  50000.0
1          102          Amit  30.00  Mumbai  60000.0
2          103         Sneha  30.75    Pune  55000.0
3          104         Priya  28.00   Delhi  57500.0
4          105         Kiran  40.00  Mumbai  65000.0

In [32]:
# Change datatype

In [33]:
df["Age"] = df["Age"].astype(int)

In [34]:
# Filtering Data

In [35]:
# Customers with Salary > 55000
high_salary = df[df["Salary"] > 55000]
print(high_salary)

   Customer_ID Customer_Name  Age    City   Salary
1          102          Amit   30  Mumbai  60000.0
3          104         Priya   28   Delhi  57500.0
4          105         Kiran   40  Mumbai  65000.0

In [36]:
# Selecting Data

In [37]:
# Single column
print(df["Customer_Name"])

0    Rahul
1     Amit
2    Sneha
3    Priya
4    Kiran
Name: Customer_Name, dtype: str

In [38]:
# Multiple columns
print(df[["Customer_Name", "Salary"]])

  Customer_Name   Salary
0         Rahul  50000.0
1          Amit  60000.0
2         Sneha  55000.0
3         Priya  57500.0
4         Kiran  65000.0

In [39]:
# Row selection
print(df.iloc[0])  # first row

Customer_ID          101
Customer_Name      Rahul
Age                   25
City                Pune
Salary           50000.0
Name: 0, dtype: object

In [40]:
# Sorting Data

In [41]:
df = df.sort_values(by="Salary", ascending=False)

In [42]:
df

   Customer_ID Customer_Name  Age    City   Salary
4          105         Kiran   40  Mumbai  65000.0
1          102          Amit   30  Mumbai  60000.0
3          104         Priya   28   Delhi  57500.0
2          103         Sneha   30    Pune  55000.0
0          101         Rahul   25    Pune  50000.0

In [43]:
# Merge Data

In [44]:
df1 = pd.DataFrame({
    "Customer_ID": [101, 102],
    "Product": ["Car", "Bike"]
})

merged = pd.merge(df, df1, on="Customer_ID", how="left")
print(merged)

   Customer_ID Customer_Name  Age    City   Salary Product
0          105         Kiran   40  Mumbai  65000.0     NaN
1          102          Amit   30  Mumbai  60000.0    Bike
2          104         Priya   28   Delhi  57500.0     NaN
3          103         Sneha   30    Pune  55000.0     NaN
4          101         Rahul   25    Pune  50000.0     Car

In [45]:
df1

   Customer_ID Product
0          101     Car
1          102    Bike

In [46]:
# Apply Function

In [47]:
def tax(salary):
    return salary * 0.05

df["Tax"] = df["Salary"].apply(tax)

In [48]:
df

   Customer_ID Customer_Name  Age    City   Salary     Tax
4          105         Kiran   40  Mumbai  65000.0  3250.0
1          102          Amit   30  Mumbai  60000.0  3000.0
3          104         Priya   28   Delhi  57500.0  2875.0
2          103         Sneha   30    Pune  55000.0  2750.0
0          101         Rahul   25    Pune  50000.0  2500.0